version: "5.1"
services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9163:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: rabbit001
    container_name: some-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - mqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  mqdata:
