// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audits.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAudit = `-- name: CreateAudit :one
insert into audits (
  id,
  created_at,
  updated_at
) values (
  gen_random_uuid(),
  now(),
  now()
)
returning id
`

func (q *Queries) CreateAudit(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAudit)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAudit = `-- name: GetAudit :one
select id, created_at, updated_at from audits
where id = $1
`

func (q *Queries) GetAudit(ctx context.Context, id uuid.UUID) (Audit, error) {
	row := q.db.QueryRowContext(ctx, getAudit, id)
	var i Audit
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
