// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_specs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const attachAuditSpecs = `-- name: AttachAuditSpecs :exec
insert into audit_specifications (audit_id,specification_id, threshold) 
select $1, $2, $3
`

type AttachAuditSpecsParams struct {
	AuditID         uuid.UUID
	SpecificationID uuid.UUID
	Threshold       int32
}

func (q *Queries) AttachAuditSpecs(ctx context.Context, arg AttachAuditSpecsParams) error {
	_, err := q.db.ExecContext(ctx, attachAuditSpecs, arg.AuditID, arg.SpecificationID, arg.Threshold)
	return err
}
