// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_specs.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const attachAuditSpecs = `-- name: AttachAuditSpecs :exec
with input_codes as (
  select unnest($2::text[]) as code
)
insert into audit_specifications (audit_id,specification_id) 
select $1, s.id
from specifications s
join input_codes i on i.code = s.code
`

type AttachAuditSpecsParams struct {
	AuditID uuid.UUID
	Column2 []string
}

func (q *Queries) AttachAuditSpecs(ctx context.Context, arg AttachAuditSpecsParams) error {
	_, err := q.db.ExecContext(ctx, attachAuditSpecs, arg.AuditID, pq.Array(arg.Column2))
	return err
}
