// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audits.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAudit = `-- name: GetAudit :one
select id, created_at, updated_at from audits
where id = $1
`

func (q *Queries) GetAudit(ctx context.Context, id uuid.UUID) (Audit, error) {
	row := q.db.QueryRowContext(ctx, getAudit, id)
	var i Audit
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
