// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_specs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertFailedSpec = `-- name: InsertFailedSpec :exec
insert into audit_result_failed_specs (
  audit_result_id,
  specification_id
) values ($1, $2)
`

type InsertFailedSpecParams struct {
	AuditResultID   uuid.UUID
	SpecificationID uuid.UUID
}

func (q *Queries) InsertFailedSpec(ctx context.Context, arg InsertFailedSpecParams) error {
	_, err := q.db.ExecContext(ctx, insertFailedSpec, arg.AuditResultID, arg.SpecificationID)
	return err
}
