// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Audit struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuditResult struct {
	ID          uuid.UUID
	AuditUserID uuid.UUID
	EntryID     uuid.UUID
	EntryName   string
	EntryPath   string
}

type AuditResultFailedSpec struct {
	AuditResultID   uuid.UUID
	SpecificationID uuid.UUID
}

type AuditSpecification struct {
	AuditID         uuid.UUID
	SpecificationID uuid.UUID
	Threshold       int32
}

type AuditUser struct {
	ID          uuid.UUID
	AuditID     uuid.UUID
	UserID      uuid.UUID
	CompletedAt time.Time
}

type Specification struct {
	ID          uuid.UUID
	Code        string
	Description string
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
