// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specifications.sql

package database

import (
	"context"
)

const getSpecificationByCode = `-- name: GetSpecificationByCode :one
select id, code, description from specifications
where code = $1
`

func (q *Queries) GetSpecificationByCode(ctx context.Context, code string) (Specification, error) {
	row := q.db.QueryRowContext(ctx, getSpecificationByCode, code)
	var i Specification
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}
